actions

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -36,7 +36,6 @@ jobs:
         os: [ubuntu-latest, windows-latest, macOS-latest]
         trx: [ ubuntu-latest, windows-latest ]
         lix: [ ubuntu-latest, macOS-latest ]
-        languages: ['cpp']
 
     outputs:
       runs-on: ${{ matrix.os }}
@@ -44,7 +43,6 @@ jobs:
       skip_run: ${{ steps.check-schedule.outputs.skip_run }}
       trex: ${{ matrix.trx }}
       linx: ${{ matrix.lix }}
-      languages: ${{ matrix.languages }}
       BFCH: ${{ steps.before-commit-hash.outputs.BEFORE_COMMIT_HASH }}
 
     runs-on: ${{ matrix.os }}
@@ -229,23 +227,11 @@ jobs:
       - name: setting up action checkout
         uses: actions/checkout@v3
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v1
-
-      - name: Login to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-
-      - name: Debug Output
+      - name: docker setup
         run: |
-          ls -R
-          pwd
-          echo "Contents of directory: $(ls)"
+          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
+          docker buildx create --use
 
       - name: Docker containerization
         uses: docker/build-push-action@v4
@@ -286,39 +272,64 @@ jobs:
          # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
 #       run: ctest
 
-  anylize:
-    name: Anylize
-    timeout-minutes: ${{ (needs.configrations.outputs.languages == 'swift' && 120) || 360 }}
-    if: needs.configrations.outputs.changes == 'true' || github.event_name == 'schedule' || (github.event_name == 'pull_request' && needs.configrations.outputs.changes == 'true')
-    strategy:
-      fail-fast: false
+  analyze:
+    name: Analyze
     # Runner size impacts CodeQL analysis time. To learn more, please see:
     #   - https://gh.io/recommended-hardware-resources-for-running-codeql
     #   - https://gh.io/supported-runners-and-hardware-resources
     #   - https://gh.io/using-larger-runners
     # Consider using larger runners for possible analysis time improvements.
-    needs: [configrations, cmake, python, cloging] # add 'testing' when you finish building up the test
-    runs-on: ubuntu-latest
+    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
+    if: needs.configrations.outputs.changes == 'true' || github.event_name == 'schedule' || (github.event_name == 'pull_request' && needs.configrations.outputs.changes == 'true')
+    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
+    permissions:
+      actions: read
+      contents: read
+      security-events: write
+
+    strategy:
+      fail-fast: false
+      matrix:
+        language: [ 'cpp' ]
+        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby', 'swift' ]
+        # Use only 'java' to analyze code written in Java, Kotlin or both
+        # Use only 'javascript' to analyze code written in JavaScript, TypeScript or both
+        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
+    - name: Checkout repository
+      uses: actions/checkout@v3
 
-      - name: Initialize CodeQL
-        uses: github/codeql-action/init@v2
-        with:
-          languages: ${{ needs.configrations.outputs.languages }}
+    # Initializes the CodeQL tools for scanning.
+    - name: Initialize CodeQL
+      uses: github/codeql-action/init@v2
+      with:
+        languages: ${{ matrix.language }}
+        # If you wish to specify custom queries, you can do so here or in a config file.
+        # By default, queries listed here will override any specified in a config file.
+        # Prefix the list here with "+" to use these queries and those in the config file.
+
+        # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
+        # queries: security-extended,security-and-quality
+
 
     # Autobuild attempts to build any compiled languages (C/C++, C#, Go, Java, or Swift).
     # If this step fails, then you should remove it and run the build manually (see below)
-
-      - name: Analysis Build
-        run: ${{ needs.build.outputs.build-script }}
+    - name: Analysis build
+      run: |
+        ${{ needs.build.outputs.build-script }}
 
     # ℹ️ Command-line programs to run using the OS shell.
     # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
 
-      - name: Perform CodeQL Analysis
-        uses: github/codeql-action/analyze@v2
-        with:
-          category: "/language:cpp"
+    #   If the Autobuild fails above, remove it and uncomment the following three lines.
+    #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.
+
+    # - run: |
+    #     echo "Run, Build Application using script"
+    #     ./location_of_script_within_repo/buildscript.sh
+
+    - name: Perform CodeQL Analysis
+      uses: github/codeql-action/analyze@v2
+      with:
+        category: "/language:${{matrix.language}}"
